module.exports = {
  INSTALLATION_COMPLETED: 'INSTALLATION_COMPLETED',
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  GET_ITEM: 'GET_ITEM',
  SET_ITEM: 'SET_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM'
}
