module.exports = {
  INSTALLATION_COMPLETED: 'INSTALLATION_COMPLETED',
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  GET_STATUS: 'GET_STATUS',
  SET_STATUS: 'SET_STATUS',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  GET_ITEM: 'GET_ITEM',
  GET_ITEMS: 'GET_ITEMS',
  SET_ITEM: 'SET_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  GET_TRANSLATIONS: 'GET_TRANSLATIONS',
  TRIGGER_NOTIFICATION: 'TRIGGER_NOTIFICATION',
  OPEN_NOTIFICATION: 'OPEN_NOTIFICATION',
  OPEN_ALL_NOTIFICATIONS: 'OPEN_ALL_NOTIFICATIONS'
}
